[package]
name = "simple-detection"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.16"

[profile.dev]
overflow-checks = false

[dependencies]
edge-detection = "0.2.6"
image = "0.25.6"
