[package]
name = "simple-detection"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.71.1"
cxx-build = "1.0"
cc = "1.2.16"
pkg-config = "0.3.32"

[profile.dev]
overflow-checks = false

[dependencies]
cxx = "1.0"

[dev-dependencies]
jpeg-encoder = "0.6.1"
zune-jpeg = "0.4.14"
